package com.example.ecommerceapp.utils.validation

import java.util.ArrayList

class Country {
    var COUNTRIES: MutableList<Country> = ArrayList()
    var code: String? = null
    var name: String? = null
    var dialCode: String? = null
    var flag = -1
    var length_min = 0
    var length_max = 1

    constructor(code: String?, name: String?, dialCode: String?, length_min: Int, length_max: Int) {
        this.code = code
        this.name = name
        this.dialCode = dialCode
        this.length_min = length_min
        this.length_max = length_max
    }

    constructor() {
        COUNTRIES.add(Country("AD", "Andorra", "+376", 0, 1))
        COUNTRIES.add(Country("AE", "United Arab Emirates", "+971", 0, 1))
        COUNTRIES.add(Country("AF", "Afghanistan", "+93", 0, 1))
        COUNTRIES.add(Country("AG", "Antigua and Barbuda", "+1", 0, 1))
        COUNTRIES.add(Country("AI", "Anguilla", "+1", 0, 1))
        COUNTRIES.add(Country("AL", "Albania", "+355", 0, 1))
        COUNTRIES.add(Country("AM", "Armenia", "+374", 0, 1))
        COUNTRIES.add(Country("AO", "Angola", "+244", 0, 1))
        COUNTRIES.add(Country("AQ", "Antarctica", "+672", 0, 1))
        COUNTRIES.add(Country("AR", "Argentina", "+54", 0, 1))
        COUNTRIES.add(Country("AS", "AmericanSamoa", "+1", 0, 1))
        COUNTRIES.add(Country("AT", "Austria", "+43", 0, 1))
        COUNTRIES.add(Country("AU", "Australia", "+61", 0, 1))
        COUNTRIES.add(Country("AW", "Aruba", "+297", 0, 1))
        COUNTRIES.add(Country("AX", "Åland Islands", "+358", 0, 1))
        COUNTRIES.add(Country("AZ", "Azerbaijan", "+994", 0, 1))
        COUNTRIES.add(Country("BA", "Bosnia and Herzegovina", "+387", 0, 1))
        COUNTRIES.add(Country("BB", "Barbados", "+1", 0, 1))
        COUNTRIES.add(Country("BD", "Bangladesh", "+880", 0, 1))
        COUNTRIES.add(Country("BE", "Belgium", "+32", 0, 1))
        COUNTRIES.add(Country("BF", "Burkina Faso", "+226", 0, 1))
        COUNTRIES.add(Country("BG", "Bulgaria", "+359", 0, 1))
        COUNTRIES.add(Country("BH", "Bahrain", "+973", 0, 1))
        COUNTRIES.add(Country("BI", "Burundi", "+257", 0, 1))
        COUNTRIES.add(Country("BJ", "Benin", "+229", 0, 1))
        COUNTRIES.add(Country("BL", "Saint Barthélemy", "+590", 0, 1))
        COUNTRIES.add(Country("BM", "Bermuda", "+1", 0, 1))
        COUNTRIES.add(Country("BN", "Brunei Darussalam", "+673", 0, 1))
        COUNTRIES.add(Country("BO", "Bolivia, Plurinational State of", "+591", 0, 1))
        COUNTRIES.add(Country("BQ", "Bonaire", "+599", 0, 1))
        COUNTRIES.add(Country("BR", "Brazil", "+55", 0, 1))
        COUNTRIES.add(Country("BS", "Bahamas", "+1", 0, 1))
        COUNTRIES.add(Country("BT", "Bhutan", "+975", 0, 1))
        COUNTRIES.add(Country("BV", "Bouvet Island", "+47", 0, 1))
        COUNTRIES.add(Country("BW", "Botswana", "+267", 0, 1))
        COUNTRIES.add(Country("BY", "Belarus", "+375", 0, 1))
        COUNTRIES.add(Country("BZ", "Belize", "+501", 0, 1))
        COUNTRIES.add(Country("CA", "Canada", "+1", 0, 1))
        COUNTRIES.add(Country("CC", "Cocos (Keeling) Islands", "+61", 0, 1))
        COUNTRIES.add(Country("CD", "Congo, The Democratic Republic of the", "+243", 0, 1))
        COUNTRIES.add(Country("CF", "Central African Republic", "+236", 0, 1))
        COUNTRIES.add(Country("CG", "Congo", "+242", 0, 1))
        COUNTRIES.add(Country("CH", "Switzerland", "+41", 0, 1))
        COUNTRIES.add(Country("CI", "Ivory Coast", "+225", 0, 1))
        COUNTRIES.add(Country("CK", "Cook Islands", "+682", 0, 1))
        COUNTRIES.add(Country("CL", "Chile", "+56", 0, 1))
        COUNTRIES.add(Country("CM", "Cameroon", "+237", 0, 1))
        COUNTRIES.add(Country("CN", "China", "+86", 0, 1))
        COUNTRIES.add(Country("CO", "Colombia", "+57", 0, 1))
        COUNTRIES.add(Country("CR", "Costa Rica", "+506", 0, 1))
        COUNTRIES.add(Country("CU", "Cuba", "+53", 0, 1))
        COUNTRIES.add(Country("CV", "Cape Verde", "+238", 0, 1))
        COUNTRIES.add(Country("CW", "Curacao", "+599", 0, 1))
        COUNTRIES.add(Country("CX", "Christmas Island", "+61", 0, 1))
        COUNTRIES.add(Country("CY", "Cyprus", "+357", 0, 1))
        COUNTRIES.add(Country("CZ", "Czech Republic", "+420", 0, 1))
        COUNTRIES.add(Country("DE", "Germany", "+49", 0, 1))
        COUNTRIES.add(Country("DJ", "Djibouti", "+253", 0, 1))
        COUNTRIES.add(Country("DK", "Denmark", "+45", 0, 1))
        COUNTRIES.add(Country("DM", "Dominica", "+1", 0, 1))
        COUNTRIES.add(Country("DO", "Dominican Republic", "+1", 0, 1))
        COUNTRIES.add(Country("DZ", "Algeria", "+213", 0, 1))
        COUNTRIES.add(Country("EC", "Ecuador", "+593", 0, 1))
        COUNTRIES.add(Country("EE", "Estonia", "+372", 0, 1))
        COUNTRIES.add(Country("EG", "Egypt", "+20", 11, 12))
        COUNTRIES.add(Country("EH", "Western Sahara", "+212", 0, 1))
        COUNTRIES.add(Country("ER", "Eritrea", "+291", 0, 1))
        COUNTRIES.add(Country("ES", "Spain", "+34", 0, 1))
        COUNTRIES.add(Country("ET", "Ethiopia", "+251", 0, 1))
        COUNTRIES.add(Country("FI", "Finland", "+358", 0, 1))
        COUNTRIES.add(Country("FJ", "Fiji", "+679", 0, 1))
        COUNTRIES.add(Country("FK", "Falkland Islands (Malvinas)", "+500", 0, 1))
        COUNTRIES.add(Country("FM", "Micronesia, Federated States of", "+691", 0, 1))
        COUNTRIES.add(Country("FO", "Faroe Islands", "+298", 0, 1))
        COUNTRIES.add(Country("FR", "France", "+33", 0, 1))
        COUNTRIES.add(Country("GA", "Gabon", "+241", 0, 1))
        COUNTRIES.add(Country("GB", "United Kingdom", "+44", 0, 1))
        COUNTRIES.add(Country("GD", "Grenada", "+1", 0, 1))
        COUNTRIES.add(Country("GE", "Georgia", "+995", 0, 1))
        COUNTRIES.add(Country("GF", "French Guiana", "+594", 0, 1))
        COUNTRIES.add(Country("GG", "Guernsey", "+44", 0, 1))
        COUNTRIES.add(Country("GH", "Ghana", "+233", 0, 1))
        COUNTRIES.add(Country("GI", "Gibraltar", "+350", 0, 1))
        COUNTRIES.add(Country("GL", "Greenland", "+299", 0, 1))
        COUNTRIES.add(Country("GM", "Gambia", "+220", 0, 1))
        COUNTRIES.add(Country("GN", "Guinea", "+224", 0, 1))
        COUNTRIES.add(Country("GP", "Guadeloupe", "+590", 0, 1))
        COUNTRIES.add(Country("GQ", "Equatorial Guinea", "+240", 0, 1))
        COUNTRIES.add(Country("GR", "Greece", "+30", 0, 1))
        COUNTRIES.add(Country("GS", "South Georgia and the South Sandwich Islands", "+500", 0, 1))
        COUNTRIES.add(Country("GT", "Guatemala", "+502", 0, 1))
        COUNTRIES.add(Country("GU", "Guam", "+1", 0, 1))
        COUNTRIES.add(Country("GW", "Guinea-Bissau", "+245", 0, 1))
        COUNTRIES.add(Country("GY", "Guyana", "+595", 0, 1))
        COUNTRIES.add(Country("HK", "Hong Kong", "+852", 0, 1))
        COUNTRIES.add(Country("HM", "Heard Island and McDonald Islands", "", 0, 1))
        COUNTRIES.add(Country("HN", "Honduras", "+504", 0, 1))
        COUNTRIES.add(Country("HR", "Croatia", "+385", 0, 1))
        COUNTRIES.add(Country("HT", "Haiti", "+509", 0, 1))
        COUNTRIES.add(Country("HU", "Hungary", "+36", 0, 1))
        COUNTRIES.add(Country("ID", "Indonesia", "+62", 0, 1))
        COUNTRIES.add(Country("IE", "Ireland", "+353", 0, 1))
        COUNTRIES.add(Country("IL", "Israel", "+972", 0, 1))
        COUNTRIES.add(Country("IM", "Isle of Man", "+44", 0, 1))
        COUNTRIES.add(Country("IN", "India", "+91", 0, 1))
        COUNTRIES.add(Country("IO", "British Indian Ocean Territory", "+246", 0, 1))
        COUNTRIES.add(Country("IQ", "Iraq", "+964", 0, 1))
        COUNTRIES.add(Country("IR", "Iran, Islamic Republic of", "+98", 0, 1))
        COUNTRIES.add(Country("IS", "Iceland", "+354", 0, 1))
        COUNTRIES.add(Country("IT", "Italy", "+39", 0, 1))
        COUNTRIES.add(Country("JE", "Jersey", "+44", 0, 1))
        COUNTRIES.add(Country("JM", "Jamaica", "+1", 0, 1))
        COUNTRIES.add(Country("JO", "Jordan", "+962", 0, 1))
        COUNTRIES.add(Country("JP", "Japan", "+81", 0, 1))
        COUNTRIES.add(Country("KE", "Kenya", "+254", 0, 1))
        COUNTRIES.add(Country("KG", "Kyrgyzstan", "+996", 0, 1))
        COUNTRIES.add(Country("KH", "Cambodia", "+855", 0, 1))
        COUNTRIES.add(Country("KI", "Kiribati", "+686", 0, 1))
        COUNTRIES.add(Country("KM", "Comoros", "+269", 0, 1))
        COUNTRIES.add(Country("KN", "Saint Kitts and Nevis", "+1", 0, 1))
        COUNTRIES.add(Country("KP", "North Korea", "+850", 0, 1))
        COUNTRIES.add(Country("KR", "South Korea", "+82", 0, 1))
        COUNTRIES.add(Country("KW", "Kuwait", "+965", 0, 1))
        COUNTRIES.add(Country("KY", "Cayman Islands", "+345", 0, 1))
        COUNTRIES.add(Country("KZ", "Kazakhstan", "+7", 0, 1))
        COUNTRIES.add(Country("LA", "Lao People\'s Democratic Republic", "+856", 0, 1))
        COUNTRIES.add(Country("LB", "Lebanon", "+961", 0, 1))
        COUNTRIES.add(Country("LC", "Saint Lucia", "+1", 0, 1))
        COUNTRIES.add(Country("LI", "Liechtenstein", "+423", 0, 1))
        COUNTRIES.add(Country("LK", "Sri Lanka", "+94", 0, 1))
        COUNTRIES.add(Country("LR", "Liberia", "+231", 0, 1))
        COUNTRIES.add(Country("LS", "Lesotho", "+266", 0, 1))
        COUNTRIES.add(Country("LT", "Lithuania", "+370", 0, 1))
        COUNTRIES.add(Country("LU", "Luxembourg", "+352", 0, 1))
        COUNTRIES.add(Country("LV", "Latvia", "+371", 0, 1))
        COUNTRIES.add(Country("LY", "Libyan Arab Jamahiriya", "+218", 0, 1))
        COUNTRIES.add(Country("MA", "Morocco", "+212", 0, 1))
        COUNTRIES.add(Country("MC", "Monaco", "+377", 0, 1))
        COUNTRIES.add(Country("MD", "Moldova, Republic of", "+373", 0, 1))
        COUNTRIES.add(Country("ME", "Montenegro", "+382", 0, 1))
        COUNTRIES.add(Country("MF", "Saint Martin", "+590", 0, 1))
        COUNTRIES.add(Country("MG", "Madagascar", "+261", 0, 1))
        COUNTRIES.add(Country("MH", "Marshall Islands", "+692", 0, 1))
        COUNTRIES.add(Country("MK", "Macedonia, The Former Yugoslav Republic of", "+389", 0, 1))
        COUNTRIES.add(Country("ML", "Mali", "+223", 0, 1))
        COUNTRIES.add(Country("MM", "Myanmar", "+95", 0, 1))
        COUNTRIES.add(Country("MN", "Mongolia", "+976", 0, 1))
        COUNTRIES.add(Country("MO", "Macao", "+853", 0, 1))
        COUNTRIES.add(Country("MP", "Northern Mariana Islands", "+1", 0, 1))
        COUNTRIES.add(Country("MQ", "Martinique", "+596", 0, 1))
        COUNTRIES.add(Country("MR", "Mauritania", "+222", 0, 1))
        COUNTRIES.add(Country("MS", "Montserrat", "+1", 0, 1))
        COUNTRIES.add(Country("MT", "Malta", "+356", 0, 1))
        COUNTRIES.add(Country("MU", "Mauritius", "+230", 0, 1))
        COUNTRIES.add(Country("MV", "Maldives", "+960", 0, 1))
        COUNTRIES.add(Country("MW", "Malawi", "+265", 0, 1))
        COUNTRIES.add(Country("MX", "Mexico", "+52", 0, 1))
        COUNTRIES.add(Country("MY", "Malaysia", "+60", 0, 1))
        COUNTRIES.add(Country("MZ", "Mozambique", "+258", 0, 1))
        COUNTRIES.add(Country("NA", "Namibia", "+264", 0, 1))
        COUNTRIES.add(Country("NC", "New Caledonia", "+687", 0, 1))
        COUNTRIES.add(Country("NE", "Niger", "+227", 0, 1))
        COUNTRIES.add(Country("NF", "Norfolk Island", "+672", 0, 1))
        COUNTRIES.add(Country("NG", "Nigeria", "+234", 0, 1))
        COUNTRIES.add(Country("NI", "Nicaragua", "+505", 0, 1))
        COUNTRIES.add(Country("NL", "Netherlands", "+31", 0, 1))
        COUNTRIES.add(Country("NO", "Norway", "+47", 0, 1))
        COUNTRIES.add(Country("NP", "Nepal", "+977", 0, 1))
        COUNTRIES.add(Country("NR", "Nauru", "+674", 0, 1))
        COUNTRIES.add(Country("NU", "Niue", "+683", 0, 1))
        COUNTRIES.add(Country("NZ", "New Zealand", "+64", 0, 1))
        COUNTRIES.add(Country("OM", "Oman", "+968", 0, 1))
        COUNTRIES.add(Country("PA", "Panama", "+507", 0, 1))
        COUNTRIES.add(Country("PE", "Peru", "+51", 0, 1))
        COUNTRIES.add(Country("PF", "French Polynesia", "+689", 0, 1))
        COUNTRIES.add(Country("PG", "Papua New Guinea", "+675", 0, 1))
        COUNTRIES.add(Country("PH", "Philippines", "+63", 0, 1))
        COUNTRIES.add(Country("PK", "Pakistan", "+92", 0, 1))
        COUNTRIES.add(Country("PL", "Poland", "+48", 0, 1))
        COUNTRIES.add(Country("PM", "Saint Pierre and Miquelon", "+508", 0, 1))
        COUNTRIES.add(Country("PN", "Pitcairn", "+872", 0, 1))
        COUNTRIES.add(Country("PR", "Puerto Rico", "+1", 0, 1))
        COUNTRIES.add(Country("PS", "Palestinian Territory, Occupied", "+970", 0, 1))
        COUNTRIES.add(Country("PT", "Portugal", "+351", 0, 1))
        COUNTRIES.add(Country("PW", "Palau", "+680", 0, 1))
        COUNTRIES.add(Country("PY", "Paraguay", "+595", 0, 1))
        COUNTRIES.add(Country("QA", "Qatar", "+974", 0, 1))
        COUNTRIES.add(Country("RE", "Réunion", "+262", 0, 1))
        COUNTRIES.add(Country("RO", "Romania", "+40", 0, 1))
        COUNTRIES.add(Country("RS", "Serbia", "+381", 0, 1))
        COUNTRIES.add(Country("RU", "Russia", "+7", 0, 1))
        COUNTRIES.add(Country("RW", "Rwanda", "+250", 0, 1))
        COUNTRIES.add(Country("SA", "Saudi Arabia", "+966", 9, 12))
        COUNTRIES.add(Country("SB", "Solomon Islands", "+677", 0, 1))
        COUNTRIES.add(Country("SC", "Seychelles", "+248", 0, 1))
        COUNTRIES.add(Country("SD", "Sudan", "+249", 0, 1))
        COUNTRIES.add(Country("SE", "Sweden", "+46", 0, 1))
        COUNTRIES.add(Country("SG", "Singapore", "+65", 0, 1))
        COUNTRIES.add(Country("SH", "Saint Helena, Ascension and Tristan Da Cunha", "+290", 0, 1))
        COUNTRIES.add(Country("SI", "Slovenia", "+386", 0, 1))
        COUNTRIES.add(Country("SJ", "Svalbard and Jan Mayen", "+47", 0, 1))
        COUNTRIES.add(Country("SK", "Slovakia", "+421", 0, 1))
        COUNTRIES.add(Country("SL", "Sierra Leone", "+232", 0, 1))
        COUNTRIES.add(Country("SM", "San Marino", "+378", 0, 1))
        COUNTRIES.add(Country("SN", "Senegal", "+221", 0, 1))
        COUNTRIES.add(Country("SO", "Somalia", "+252", 0, 1))
        COUNTRIES.add(Country("SR", "Suriname", "+597", 0, 1))
        COUNTRIES.add(Country("SS", "South Sudan", "+211", 0, 1))
        COUNTRIES.add(Country("ST", "Sao Tome and Principe", "+239", 0, 1))
        COUNTRIES.add(Country("SV", "El Salvador", "+503", 0, 1))
        COUNTRIES.add(Country("SX", "Sint Maarten", "+1", 0, 1))
        COUNTRIES.add(Country("SY", "Syrian Arab Republic", "+963", 0, 1))
        COUNTRIES.add(Country("SZ", "Swaziland", "+268", 0, 1))
        COUNTRIES.add(Country("TC", "Turks and Caicos Islands", "+1", 0, 1))
        COUNTRIES.add(Country("TD", "Chad", "+235", 0, 1))
        COUNTRIES.add(Country("TF", "French Southern Territories", "+262", 0, 1))
        COUNTRIES.add(Country("TG", "Togo", "+228", 0, 1))
        COUNTRIES.add(Country("TH", "Thailand", "+66", 0, 1))
        COUNTRIES.add(Country("TJ", "Tajikistan", "+992", 0, 1))
        COUNTRIES.add(Country("TK", "Tokelau", "+690", 0, 1))
        COUNTRIES.add(Country("TL", "East Timor", "+670", 0, 1))
        COUNTRIES.add(Country("TM", "Turkmenistan", "+993", 0, 1))
        COUNTRIES.add(Country("TN", "Tunisia", "+216", 0, 1))
        COUNTRIES.add(Country("TO", "Tonga", "+676", 0, 1))
        COUNTRIES.add(Country("TR", "Turkey", "+90", 0, 1))
        COUNTRIES.add(Country("TT", "Trinidad and Tobago", "+1", 0, 1))
        COUNTRIES.add(Country("TV", "Tuvalu", "+688", 0, 1))
        COUNTRIES.add(Country("TW", "Taiwan", "+886", 0, 1))
        COUNTRIES.add(Country("TZ", "Tanzania, United Republic of", "+255", 0, 1))
        COUNTRIES.add(Country("UA", "Ukraine", "+380", 0, 1))
        COUNTRIES.add(Country("UG", "Uganda", "+256", 0, 1))
        COUNTRIES.add(Country("UM", "U.S. Minor Outlying Islands", "", 0, 1))
        COUNTRIES.add(Country("US", "United States", "+1", 0, 1))
        COUNTRIES.add(Country("UY", "Uruguay", "+598", 0, 1))
        COUNTRIES.add(Country("UZ", "Uzbekistan", "+998", 0, 1))
        COUNTRIES.add(Country("VA", "Holy See (Vatican City State)", "+379", 0, 1))
        COUNTRIES.add(Country("VC", "Saint Vincent and the Grenadines", "+1", 0, 1))
        COUNTRIES.add(Country("VE", "Venezuela, Bolivarian Republic of", "+58", 0, 1))
        COUNTRIES.add(Country("VG", "Virgin Islands, British", "+1", 0, 1))
        COUNTRIES.add(Country("VI", "Virgin Islands, U.S.", "+1", 0, 1))
        COUNTRIES.add(Country("VN", "Viet Nam", "+84", 0, 1))
        COUNTRIES.add(Country("VU", "Vanuatu", "+678", 0, 1))
        COUNTRIES.add(Country("WF", "Wallis and Futuna", "+681", 0, 1))
        COUNTRIES.add(Country("WS", "Samoa", "+685", 0, 1))
        COUNTRIES.add(Country("XK", "Kosovo", "+383", 0, 1))
        COUNTRIES.add(Country("YE", "Yemen", "+967", 0, 1))
        COUNTRIES.add(Country("YT", "Mayotte", "+262", 0, 1))
        COUNTRIES.add(Country("ZA", "South Africa", "+27", 0, 1))
        COUNTRIES.add(Country("ZM", "Zambia", "+260", 0, 1))
        COUNTRIES.add(Country("ZW", "Zimbabwe", "+263", 0, 1))
    }

    fun getCountry(code: String): Country? {
        for (i in COUNTRIES.indices) {
            if (COUNTRIES[i].code == code) {
                return COUNTRIES[i]
            }
        }
        return null
    }

    companion object {
        var allCountriesList: List<Country>? = null
    }
}